INSERT INTO APP_USER (pseudo, age)
VALUES ('Darryl', 42),
    ('Dwight', 48),
    ('Angela', 43),
    ('Oscar', 55),
    ('Ryan', 34),
    ('Kelly', 34),
    ('Andy', 40),
    ('Erin', 34),
    ('Jim', 34),
    ('Pam', 40),
    ('Michael', 51),
    ('Kevin', 41),
    ('Stanley', 58),
    ('Meredith', 50),
    ('Creed', 71);